package com.iris.dao;

import com.iris.model.UserMoneyDetail;
import com.iris.model.UserMoneyDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMoneyDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    long countByExample(UserMoneyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    int deleteByExample(UserMoneyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    int insert(UserMoneyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    int insertSelective(UserMoneyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    List<UserMoneyDetail> selectByExample(UserMoneyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    UserMoneyDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserMoneyDetail record, @Param("example") UserMoneyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    int updateByExample(@Param("record") UserMoneyDetail record, @Param("example") UserMoneyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    int updateByPrimaryKeySelective(UserMoneyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_detail
     *
     * @mbg.generated Tue May 22 20:52:09 CST 2018
     */
    int updateByPrimaryKey(UserMoneyDetail record);
}