package com.iris.model;

import java.util.Date;

public class SysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    private Integer id;
    private String username;
    private String password;
    private Date created;
    private Byte flag;
    private Date updated;
    private Integer createdUser;
    private Integer updatedUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.username
     *
     * @return the value of sys_user.username
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.username
     *
     * @param username the value for sys_user.username
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.created
     *
     * @return the value of sys_user.created
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.created
     *
     * @param created the value for sys_user.created
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.flag
     *
     * @return the value of sys_user.flag
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.flag
     *
     * @param flag the value for sys_user.flag
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.updated
     *
     * @return the value of sys_user.updated
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.updated
     *
     * @param updated the value for sys_user.updated
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.created_user
     *
     * @return the value of sys_user.created_user
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public Integer getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.created_user
     *
     * @param createdUser the value for sys_user.created_user
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.updated_user
     *
     * @return the value of sys_user.updated_user
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public Integer getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.updated_user
     *
     * @param updatedUser the value for sys_user.updated_user
     *
     * @mbg.generated Fri Jul 14 19:03:54 CST 2017
     */
    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }
}