package com.iris.model;

import java.util.Date;

public class UserMoneyDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_money_detail.ID
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_money_detail.USER_ID
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_money_detail.GOODS_NAME
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_money_detail.MONEY
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_money_detail.TYPE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_money_detail.MONEY_STATUS
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    private Integer moneyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_money_detail.DESCRIBE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_money_detail.CREATE_DATE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_money_detail.MAKE_DATE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    private Date makeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_money_detail.DELETE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    private Integer delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_money_detail.ID
     *
     * @return the value of user_money_detail.ID
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_money_detail.ID
     *
     * @param id the value for user_money_detail.ID
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_money_detail.USER_ID
     *
     * @return the value of user_money_detail.USER_ID
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_money_detail.USER_ID
     *
     * @param userId the value for user_money_detail.USER_ID
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_money_detail.GOODS_NAME
     *
     * @return the value of user_money_detail.GOODS_NAME
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_money_detail.GOODS_NAME
     *
     * @param goodsName the value for user_money_detail.GOODS_NAME
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_money_detail.MONEY
     *
     * @return the value of user_money_detail.MONEY
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_money_detail.MONEY
     *
     * @param money the value for user_money_detail.MONEY
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_money_detail.TYPE
     *
     * @return the value of user_money_detail.TYPE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_money_detail.TYPE
     *
     * @param type the value for user_money_detail.TYPE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_money_detail.MONEY_STATUS
     *
     * @return the value of user_money_detail.MONEY_STATUS
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public Integer getMoneyStatus() {
        return moneyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_money_detail.MONEY_STATUS
     *
     * @param moneyStatus the value for user_money_detail.MONEY_STATUS
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public void setMoneyStatus(Integer moneyStatus) {
        this.moneyStatus = moneyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_money_detail.DESCRIBE
     *
     * @return the value of user_money_detail.DESCRIBE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_money_detail.DESCRIBE
     *
     * @param describe the value for user_money_detail.DESCRIBE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_money_detail.CREATE_DATE
     *
     * @return the value of user_money_detail.CREATE_DATE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_money_detail.CREATE_DATE
     *
     * @param createDate the value for user_money_detail.CREATE_DATE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_money_detail.MAKE_DATE
     *
     * @return the value of user_money_detail.MAKE_DATE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public Date getMakeDate() {
        return makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_money_detail.MAKE_DATE
     *
     * @param makeDate the value for user_money_detail.MAKE_DATE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public void setMakeDate(Date makeDate) {
        this.makeDate = makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_money_detail.DELETE
     *
     * @return the value of user_money_detail.DELETE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_money_detail.DELETE
     *
     * @param delete the value for user_money_detail.DELETE
     *
     * @mbg.generated Mon Jun 11 19:22:46 CST 2018
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }
}